### PR TITLE
Fix performances when updating a category and dispatch the update to the sidebar and shoppingList

### LINKED ISSUE #104: FIX: Items page, items state remounting issues
Just copying from discord:
If you put useEffect and use it on mount and unmount of the component, you will see all of the item and category title components gets unmounted multiple times on every update of single category title :confused: Also happens when you edit a single item, all of the items and category titles get unmounted...

### PR DESCRIPTION
**Pull request by ips-coding-challenge**
closes #104

### CODE REVIEW

File: src/pages/items/ItemsPage.tsx [hunk 1]
```diff
@@ -186,14 +145,13 @@ const ItemsPage: React.FC = () => {
                             <CategoryTitle
```
Comment (fajfara) [inline src/pages/items/ItemsPage.tsx:145]: I think we should also rename this component to CategoryTitleEditable or CategoryHeadingEditable

File: src/components/item-sidebars/ShowItemSidebar.tsx [hunk 2]
```diff
@@ -14,6 +14,12 @@ import Button from '../button/Button'
 import { MdModeEdit } from 'react-icons/md'
 import { LazyLoadImage } from 'react-lazy-load-image-component'
 import 'react-lazy-load-image-component/src/effects/blur.css'
+import { singleCategoryState } from '../../global-state/categoriesState'
+
+const CategoryText = ({ category_id }: any) => {
+    const singleCategory = useRecoilValue(singleCategoryState(category_id))
+    return <div className="text-xl mt-2">{singleCategory.name}</div>
+}
```
Comment (fajfara) [inline src/components/item-sidebars/ShowItemSidebar.tsx:22]: I feel like this can be refactored. I would just take the CategoryHeading component, have 2 props, one for category_id, and another for heading props, which would be an object which can be spread over Heading component.

**Review by fajfara — CHANGES_REQUESTED** [review]

File: src/components/item-sidebars/ShowItemSidebar.tsx (hunk 2 above)
Comment (ips-coding-challenge) [reply src/components/item-sidebars/ShowItemSidebar.tsx:22]: I will look into that. I actually tried with a HOC component but didn't end up with something that I liked. But I'm not sure that I did it correctly anyway ;).
